# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_exchange_peering_db_id'),
        ('peers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.Exchange'),
            preserve_default=False,
        ),
    ]
