# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='vendor',
            field=models.CharField(choices=[('junos', 'Junos'), ('arista', 'Arista')], default='Junos', max_length=10),
        ),
    ]
