# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_exchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='exchange',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
