# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20170604_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='peering_db_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
